### ISSUE TITLE
Mail Ale

### ISSUE THREAD

**Issue by fcancel** [7547-G2/BOComercio#4]
Hola Javier y equipo,

El control "Agregar >" y "< Quitar" son botones? qué hacen?
Esto deberia explicarse con los criterios de aceptación.
Esos adicionales aplican a qué plato? no queda claro en esa pantalla.

"No considerar como estan distribuidos los controles", por qué?

Dicen que se entiende, pero a mi no me queda claro. Veo desprolijo estos envíos parciales a última hora del domingo con de prototipos en partes, con diferentes herramientas sin historias de usuarios ni criterios de aceptación asociados, cuando mañana es la entrega formal. 

Saludos

**Comment by jaschulz** [comment]
Resuelto. Tal como lo solicitó, están explicados en los criterios de aceptación.
